export const cases = [
    {
        "client_phone": "string",
        "client_email": "user@example.com",
        "address": "string",
        "client_first_name": "string",
        "client_last_name": "string",
        "type_of_property": "string",
        "floor": 0,
        "elevator": 0,
        "squaremeters": 0,
        "quantity": 0,
        "way_to_property": "string",
        "create_time": "2022-10-25T07:51:12.756Z",
        "assigned_time": "2022-10-25T07:51:12.756Z",
        "confirmed_time": "2022-10-25T07:51:12.756Z",
        "state_id": 0,
        "state": "string",
        "inspector_id": 0,
        "inspector": "string",
        "manager_id": 0,
        "manager": "string"
    },
    {
        "client_phone": "string",
        "client_email": "user@example.com",
        "address": "string",
        "client_first_name": "string",
        "client_last_name": "string",
        "type_of_property": "string",
        "floor": 0,
        "elevator": 0,
        "squaremeters": 0,
        "quantity": 0,
        "way_to_property": "string",
        "create_time": "2022-10-25T07:51:12.756Z",
        "assigned_time": "2022-10-25T07:51:12.756Z",
        "confirmed_time": "2022-10-25T07:51:12.756Z",
        "state_id": 0,
        "state": "string",
        "inspector_id": 0,
        "inspector": "string",
        "manager_id": 0,
        "manager": "string"
    },
    {
        "client_phone": "string",
        "client_email": "user@example.com",
        "address": "string",
        "client_first_name": "string",
        "client_last_name": "string",
        "type_of_property": "string",
        "floor": 0,
        "elevator": 0,
        "squaremeters": 0,
        "quantity": 0,
        "way_to_property": "string",
        "create_time": "2022-10-25T07:51:12.756Z",
        "assigned_time": "2022-10-25T07:51:12.756Z",
        "confirmed_time": "2022-10-25T07:51:12.756Z",
        "state_id": 0,
        "state": "string",
        "inspector_id": 0,
        "inspector": "string",
        "manager_id": 0,
        "manager": "string"
    }
]